export const constants={
    GET_EVIDENCES:'GET_EVIDENCES',
    FETCH_USERS:'FETCH_USERS',
    GET_EVIDENCE_REQUESTS:'GET_EVIDENCE_REQUESTS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    POPULATION_FETCH:'POPULATION_FETCH',
    GET_USER_EVIDENCES:'GET_USER_EVIDENCES',
    MY_EVIDENCE_REQUESTS:'MY_EVIDENCE_REQUESTS',
    CASE_FETCH:'CASE_FETCH',
    PAY_FETCH:'PAY_FETCH',
    APP_FETCH:'APP_FETCH'

}